CREATE TABLE `wp_yoast_seo_links` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,  `post_id` bigint(20) unsigned NOT NULL,  `target_post_id` bigint(20) unsigned NOT NULL,  `type` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,  PRIMARY KEY (`id`),  KEY `link_direction` (`post_id`,`type`)) ENGINE=MyISAM AUTO_INCREMENT=58 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_yoast_seo_links` DISABLE KEYS */;
INSERT INTO `wp_yoast_seo_links` VALUES('49', 'https://www.weddingwire.com/biz/maui-beats-paia/69ba6b2f384df3ca.html', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('48', 'https://www.jbrave.net/', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('47', 'https://www.weddingwire.com/reviews/la-beats-djs-los-angeles/69ba6b2f384df3ca.html', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('46', 'https://www.weddingwire.com/reviews/maui-beats-paia/69ba6b2f384df3ca.html', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('45', 'https://www.weddingwire.com/reviews/maui-beats-paia/69ba6b2f384df3ca.html', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('44', 'https://www.weddingwire.com/reviews/maui-beats-paia/69ba6b2f384df3ca.html', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('43', 'https://www.weddingwire.com/reviews/maui-beats-paia/69ba6b2f384df3ca.html', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('41', '/private-parties', '2', '4000', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('42', '/private-parties', '2', '4000', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('40', '/la-company-events', '2', '3983', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('38', '/la-wedding', '2', '238', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('39', '/la-company-events', '2', '3983', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('37', '/la-wedding', '2', '238', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('36', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('35', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('34', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('33', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('32', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('30', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('31', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('29', '/#contact', '2', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('50', 'https://www.weddingwire.com', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('51', 'http://3-deep-breaths.com/', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('52', 'http://3-deep-breaths.com/', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('53', 'http://3-deep-breaths.com/', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('54', 'https://www.facebook.com/LABeatsDJs/', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('55', 'https://plus.google.com/113508098901270898467', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('56', 'https://www.youtube.com/channel/UCN7Z9e-A2ha4O1xX7dbb7XQ', '2', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('57', 'https://www.yelp.com/biz/la-beats-djs-los-angeles', '2', '0', 'external');
/*!40000 ALTER TABLE `wp_yoast_seo_links` ENABLE KEYS */;
